stages:
  - publish
  - deliver
  - deploy

mirror:
  stage: publish
  script:
    - setsid ./ci/mirror.sh
  only:
    - /^(main.*)$/
  tags:
    - mirror

code-server:
  stage: deliver
  script:
    - setsid ./ci/docker-deliver.sh "code-server" "3.12.0" "1.3"
  only:
    refs:
      - /^(main.*)$/
    changes:
      - ci/docker-deliver.sh
      - docker-compose-build.yml
      - Dockerfile
  tags:
    - imagesbuilder
