stages:
  - publish
  - deliver
  - deploy

mirror:
  stage: publish
  script:
    - setsid ./ci/mirror.sh
  only:
    - /^(main.*)$/
  tags:
    - mirror

code-server:
  stage: deliver
  script:
    - setsid ./ci/docker-deliver.sh "code-server" "4.9.1" "1.5"
  only:
    refs:
      - /^(main.*)$/
    changes:
      - .gitlab-ci.yml
      - ci/docker-deliver.sh
      - docker-compose-build.yml
      - Dockerfile
      - bash_config.sh
  tags:
    - imagesbuilder
