version: "3.3"

services: 
  code-server:
    image: comworkio/code-server:latest
    build: 
      context: .
      dockerfile: Dockerfile
      target: code-server
      args:
        CODE_SERVER_VERSION: ${CODE_SERVER_VERSION}
        NODE_VERSION: 16.13.0
        YQ_VERSION: 4.16.2
        TERRAGRUNT_VERSION: 0.35.16
        OS: linux
        OS_ARCH: amd64
        NODE_ARCH: x64
