version: "3.3"

services: 
  code-server:
    image: comworkio/code-server:latest
    build: 
      context: .
      dockerfile: Dockerfile
      target: code-server
      args:
        CODE_SERVER_VERSION: ${CODE_SERVER_VERSION}
        NODE_VERSION: 16.13.0
        NODE_ARCH: x64
        NODE_OS: linux
