version: "3.3"

services: 
  code-server:
    image: comworkio/code-server:latest
    build: 
      context: .
      dockerfile: Dockerfile
      target: code-server
      args:
        CODE_SERVER_VERSION: ${CODE_SERVER_VERSION}
        NODE_VERSION: 18.14.0
        YQ_VERSION: 4.30.8
        TERRAGRUNT_VERSION: 0.43.2
        HELM_VERSION: 3.11.0
        K9S_VERSION: 0.27.2
        OS: linux
        OS_ARCH: amd64
        NODE_ARCH: x64
        K9S_OS: Linux
        K9S_ARCH: amd64
        KUBESEAL_VERSION: 0.19.4
        KUBESEAL_ARCH: amd64
        MC_ARCH: amd64
        CWC_VERSION: 1.6.7
        CWC_ARCH: amd64
