
---
- name: Create coder folders
  become: yes
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    recurse: "{{ item.recurse }}"
  with_items:
    - { path: "{{ node_home }}/extensions", recurse: no, mode: '0777'}

- name: Create coder files
  become: yes
  template:
    src: "{{ item.template }}.j2"
    dest: "{{ item.path }}/{{ item.template }}"
    mode: "{{ item.mode }}"
    group: docker
  with_items:
    - { template: docker-compose-code.yml , path: "{{ node_home }}", mode: '0644' }
    - { template: Dockerfile.code , path: "{{ node_home }}", mode: '0644' }
    - { template: code_start.sh , path: "{{ node_home }}", mode: '0755' }
    - { template: code-config.yaml , path: "{{ node_home }}", mode: '0755' }
    - { template: settings.json , path: "{{ node_home }}", mode: '0777' }

- name: Run the container
  become: yes
  command: "bash {{ node_home }}/code_start.sh"
